export enum Attribute {
  FREE_OFF_SEASON = 'FREE_OFF_SEASON',
  DANGEROUS_AREA = 'DANGEROUS_AREA',
  POOR_SURFACE = 'POOR_SURFACE',
  HARD_ACCESS = 'HARD_ACCESS',
  FLOOD_PRONE = 'FLOOD_PRONE',
  POOR_LIGHTING = 'POOR_LIGHTING',
  PARKING_RESTRICTIONS = 'PARKING_RESTRICTIONS',
}
