export enum PoiActionsEnum {
  UPDATE_LOCATION = 'UPDATE_LOCATION',
  DISMISS = 'DISMISS',
  CANCEL = 'CANCEL',
  NAVIGATE = 'NAVIGATE',
  CONFIRM = 'CONFIRM',
  VIEW_REVIEWS = 'VIEW_REVIEWS',
  ADD_REVIEW = 'ADD_REVIEW',
}
